"""empty message

Revision ID: c9c886e840d9
Revises: 
Create Date: 2019-01-10 13:12:18.011923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c886e840d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('sample_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spectral_library', sa.String(length=256), nullable=True),
    sa.Column('class_mineral', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('image_link', sa.String(), nullable=True),
    sa.Column('wavelength_range', sa.String(length=128), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('extension', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('spectra',
    sa.Column('spectrum_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('instrument', sa.String(length=128), nullable=True),
    sa.Column('measurement', sa.String(length=128), nullable=True),
    sa.Column('x_unit', sa.String(length=128), nullable=True),
    sa.Column('y_unit', sa.String(length=128), nullable=True),
    sa.Column('min_wavelength', sa.Float(), nullable=True),
    sa.Column('max_wavelength', sa.Float(), nullable=True),
    sa.Column('num_values', sa.Integer(), nullable=True),
    sa.Column('additional_information', sa.TEXT(), nullable=True),
    sa.Column('x_data', sa.LargeBinary(), nullable=True),
    sa.Column('y_data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spectrum_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spectra')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('samples')
    # ### end Alembic commands ###
